[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
upload_port = /dev/ttyUSB0
monitor_speed = 115200
framework = arduino
board_build.filesystem = littlefs

; Increase flash for web UI + LittleFS
board_build.ldscript = eagle.flash.4m2m.ld

lib_deps =
  adafruit/Adafruit SSD1306@^2.5.16
  miguelbalboa/MFRC522@^1.4.12
  bblanchon/ArduinoJson@^7.0.0